
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:templates/pages/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://springboot-webservice3.c8fut6pj2ay8.ap-northeast-2.rds.amazonaws.com:3306/photogram?serverTimezone=Asia/Seoul
    username: james
    password: jms990501

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
  devtools:
    restart:
      enabled: true
    liveload:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

file:
  path: C:/Users/alstj/workspace/photogram/upload/

